# Generated by Django 5.2.5 on 2025-08-27 17:41

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContractEmployee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_code', models.CharField(editable=False, max_length=20, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('age', models.PositiveIntegerField(blank=True, null=True)),
                ('telephone', models.CharField(blank=True, max_length=50, null=True)),
                ('department', models.CharField(blank=True, max_length=100, null=True)),
                ('job_position', models.CharField(blank=True, max_length=100, null=True)),
                ('salary_birr', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('nationality', models.CharField(blank=True, max_length=100, null=True)),
                ('marital_status', models.CharField(blank=True, choices=[('SINGLE', 'Single'), ('MARRIED', 'Married'), ('OTHER', 'Other')], max_length=20, null=True)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('sub_city', models.CharField(blank=True, max_length=100, null=True)),
                ('wereda', models.CharField(blank=True, max_length=100, null=True)),
                ('tin_no', models.CharField(blank=True, max_length=50, null=True)),
                ('working_hour', models.CharField(blank=True, choices=[('NORMAL', 'Normal Hour'), ('PART', 'Part Time'), ('MORNING', 'Morning'), ('AFTERNOON', 'Afternoon'), ('NIGHT', 'Night'), ('SHIFTING', 'Shifting')], max_length=50, null=True)),
                ('branch', models.CharField(blank=True, max_length=100, null=True)),
                ('hire_date', models.DateField(blank=True, null=True)),
                ('contract_date', models.DateField(default=django.utils.timezone.now)),
                ('end_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'ordering': ['contract_date', 'name'],
            },
        ),
        migrations.CreateModel(
            name='PermanentEmployee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_code', models.CharField(editable=False, max_length=20, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('age', models.PositiveIntegerField(blank=True, null=True)),
                ('telephone', models.CharField(blank=True, max_length=50, null=True)),
                ('department', models.CharField(blank=True, max_length=100, null=True)),
                ('job_position', models.CharField(blank=True, max_length=100, null=True)),
                ('salary_birr', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('nationality', models.CharField(blank=True, max_length=100, null=True)),
                ('marital_status', models.CharField(blank=True, choices=[('SINGLE', 'Single'), ('MARRIED', 'Married'), ('OTHER', 'Other')], max_length=20, null=True)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('sub_city', models.CharField(blank=True, max_length=100, null=True)),
                ('wereda', models.CharField(blank=True, max_length=100, null=True)),
                ('tin_no', models.CharField(blank=True, max_length=50, null=True)),
                ('working_hour', models.CharField(blank=True, choices=[('NORMAL', 'Normal Hour'), ('PART', 'Part Time'), ('MORNING', 'Morning'), ('AFTERNOON', 'Afternoon'), ('NIGHT', 'Night'), ('SHIFTING', 'Shifting')], max_length=50, null=True)),
                ('branch', models.CharField(blank=True, max_length=100, null=True)),
                ('hire_date', models.DateField(blank=True, null=True)),
                ('fired_date', models.DateField(blank=True, null=True)),
                ('terminated', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['fired_date', 'name'],
            },
        ),
        migrations.CreateModel(
            name='TemporaryEmployee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_code', models.CharField(editable=False, max_length=20, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('age', models.PositiveIntegerField(blank=True, null=True)),
                ('telephone', models.CharField(blank=True, max_length=50, null=True)),
                ('department', models.CharField(blank=True, max_length=100, null=True)),
                ('job_position', models.CharField(blank=True, max_length=100, null=True)),
                ('salary_birr', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('nationality', models.CharField(blank=True, max_length=100, null=True)),
                ('marital_status', models.CharField(blank=True, choices=[('SINGLE', 'Single'), ('MARRIED', 'Married'), ('OTHER', 'Other')], max_length=20, null=True)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('sub_city', models.CharField(blank=True, max_length=100, null=True)),
                ('wereda', models.CharField(blank=True, max_length=100, null=True)),
                ('tin_no', models.CharField(blank=True, max_length=50, null=True)),
                ('working_hour', models.CharField(blank=True, choices=[('NORMAL', 'Normal Hour'), ('PART', 'Part Time'), ('MORNING', 'Morning'), ('AFTERNOON', 'Afternoon'), ('NIGHT', 'Night'), ('SHIFTING', 'Shifting')], max_length=50, null=True)),
                ('branch', models.CharField(blank=True, max_length=100, null=True)),
                ('hire_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TemporaryWorkLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_type', models.CharField(choices=[('DAILY', 'Daily'), ('WEEKLY', 'Weekly'), ('MONTHLY', 'Monthly')], max_length=10)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('recorded_value', models.DecimalField(blank=True, decimal_places=2, help_text='e.g., hours or pay amount', max_digits=12, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='base.temporaryemployee')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
